### ISSUE TITLE
REST API post calls return empty body

### ISSUE THREAD

**Issue by perotom** [Dolibarr/dolibarr#12761]
# Bug
The response body for REST API Post calls is empty.

## Environment
- **Version**: 10.0.2, 10.0.4, and maybe 10.0.*?

## Expected and actual behavior
Response body should contain created entity. Actual response is empty.

## Steps to reproduce the behavior
Fire up docker-compose:
```
mariadb:
  image: mariadb:latest
  command: --character_set_client=utf8 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --character-set-client-handshake=FALSE
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: dolibarr

web:
  image: upshift/dolibarr:10.0.2
  environment:
    DOLI_DB_HOST: mariadb
    DOLI_DB_USER: root
    DOLI_DB_PASSWORD: root
    DOLI_DB_NAME: dolibarr
    DOLI_ADMIN_LOGIN: admin
    DOLI_ADMIN_PASSWORD: password
    DOLI_URL_ROOT: 'http://localhost:8000'
    PHP_INI_DATE_TIMEZONE: 'Europe/Paris'
  ports:
    - "8000:80"
  links:
    - mariadb
```
Finish installation. Enable REST API and Third parties plugin for example. Use the API explorer to create a new contact for example. The `Response Code` will be `200` but the `Response Body` will be `{}`. If you list the contacts the created entity is visible.
