### ISSUE TITLE
Can't see permissions related to the user module in the page to assign permission to user

### ISSUE THREAD

**Issue by vincentjdc** [Dolibarr/dolibarr#18734]
# Bug
It the permission settings page of a user (`/user/perms.php?id=...`), the list of permissions related to a user (`user->lire`, `user->creer`, ...) are not displayed and so can't be assigned to a user.

## Environment
- **Version**: 14
- **URL(s)**: `/user/perms.php?id=...`

## Expected and actual behavior
The page should allow the admin to assign permissions related to users.

## Steps to reproduce the behavior
- Install fresh v14 of dolibarr
- As admin, create a new user
- Edit the perms of the user

**Comment by ksar-ksar** [comment]
Hi,

I have created a new user on a V14.0.3, and permissions settings are displayed
![image](https://user-images.githubusercontent.com/35605507/134349931-81c406b2-5c54-44ad-9b83-6ded24966e33.png)

**Comment by vincentjdc** [comment]
I'm using the following docker image : https://hub.docker.com/r/tuxgasy/dolibarr/ with the following docker-compose configuration : 
```yaml

version: '3.4'

services:
    mariadb:
        image: mariadb:latest
        container_name: dolibarr-bug-db
        ports:
            - "127.0.0.1:${DOLIBARR_DB_PORT}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        volumes:
            - ./mysql_data:/var/lib/mysql
    web:
        image: tuxgasy/dolibarr:latest
        container_name: dolibarr-bug
        ports:
            - "127.0.0.1:${DOLIBARR_PORT}:80"
        environment:
            DOLI_DB_HOST: mariadb
            DOLI_DB_USER: ${DOLI_DB_USER}
            DOLI_DB_PASSWORD: ${DOLI_DB_PASSWORD}
            DOLI_DB_NAME: ${DOLI_DB_NAME}
            DOLI_URL_ROOT: ${DOLI_URL_ROOT}
            PHP_INI_DATE_TIMEZONE: 'Europe/Brussels'
            DOLI_ADMIN_LOGIN: ${DOLI_ADMIN_LOGIN}
            DOLI_ADMIN_PASSWORD: ${DOLI_ADMIN_PASSWORD}
        links:
            - mariadb

```
and .env file
```
COMPOSE_PROJECT_NAME=dolibarr-bug

MYSQL_ROOT_PASSWORD=superrootpassword
MYSQL_DATABASE=dolibarr

DOLI_DB_USER=root
DOLI_DB_PASSWORD=superpassword
DOLI_DB_NAME=dolibarr
DOLIBARR_DB_PORT=3313
DOLI_URL_ROOT=http://localhost
DOLIBARR_PORT=84
DOLIBARR_VERSION=14
DOLI_ADMIN_LOGIN=admin
DOLI_ADMIN_PASSWORD=another superpassword

```

```sh
docker-compose up -d
```

After that, Dolibarr is running using 14.0.2. I can login as admin but can't see user permissions : 

![Capture du 2021-09-22 16-04-25](https://user-images.githubusercontent.com/50613035/134358770-05e8ca6d-ac89-462a-980c-dad6c37a8d01.png)

**Comment by ksar-ksar** [comment]
Hello,

Seems to be a "blank page" = Check the apache logs.

**Comment by vincentjdc** [comment]
Not sure. If I activate other module, I see theirs perms : 

![Capture du 2021-09-22 16-43-25](https://user-images.githubusercontent.com/50613035/134365764-017914fe-6d09-4c2a-a357-86b011c659a3.png)

Apache logs does not seems to be relevant.

![Capture du 2021-09-22 16-47-05](https://user-images.githubusercontent.com/50613035/134366202-f7cab3d5-26b0-4dad-84d9-0a7039da54af.png)

Did you mean dolibarr.log ?

**Comment by ksar-ksar** [comment]
No I meant Apache error log, what you display is access log.

**Comment by vincentjdc** [comment]
I'm using `docker logs` to get the dolibarr's container logs. It displays errors and access. I get no errors.

I also tried the following :
- stopping the container
- Downloading dolibarr's code directly from Github (14.0.2 zip file)
- mapping the source code using a docker volume
- deleting mysql_data folder so that a new one will be created on the container start
- start the container

I've the same result.

**Comment by hanneshier** [comment]
I have the same problem on Dolibarr 15.0.1. I cannot the see the Permissions related to "Users & Groups". I use the Dolibarr -> LDAP Sync.

![Screenshot 2022-05-17 at 16 09 33](https://user-images.githubusercontent.com/11063798/168831609-86a9f1ed-e02e-40d5-8384-4cf6f5cd056d.png)

**Comment by hanneshier** [comment]
I still can't find the permissions. Here is my docker-compose config:

```
version: "2.2"

services:

  dolibarr:
    image: tuxgasy/dolibarr:latest
    container_name: dolibarr
    restart: unless-stopped
    depends_on:
      - "mysql"
    environment:
      # Database
      DOLI_DB_HOST: "mysql"
      DOLI_DB_USER: "dolibarr"
      DOLI_DB_PASSWORD: "supersecurepasswrd"
      DOLI_DB_NAME: "dolibarr"
      # General
      DOLI_URL_ROOT: "https://dolibarr.example.com"
      DOLI_ADMIN_LOGIN: "admin"
      DOLI_ADMIN_PASSWORD: "evenmoresecurepassword"
      # LDAP
      DOLI_AUTH: "ldap, dolibarr"
      DOLI_LDAP_HOST: "openldap"
      DOLI_LDAP_DN: "ou=people,dc=example,dc=com"
      DOLI_LDAP_BIND_DN: "cn=dolibarr,ou=dsa,dc=example,dc=com"
      DOLI_LDAP_BIND_PASS: "mostsecurepassword"
      DOLI_LDAP_FILTER: "&(objectClass=inetOrgPerson)"
      # URL Proxy
      VIRTUAL_HOST: dolibarr.example.com
      LETSENCRYPT_HOST: dolibarr.example.com
      LETSENCRYPT_EMAIL: letsencrypt@example.com
    volumes:
      - ./docker-data/dolibarr:/var/www/documents
      - ./docker-data/theme:/var/www/htdocs/theme/mytheme
      - ./docker-data/plugin/cdav:/var/www/htdocs/cdav
    networks:
      - proxy
      - ldap
      - backend

  mysql:
    image: library/mariadb:latest
    container_name: dolibarr_db
    restart: unless-stopped
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: "dolibarr"
      MYSQL_USER: "dolibarr"
      MYSQL_PASSWORD: "supersecurepasswrd"
    volumes:
      - ./docker-data/db:/var/lib/mysql
    networks:
      - backend

networks:
  proxy:
    external:
      name: proxy
  ldap:
    external:
      name: ldap
  backend:
```
