### ISSUE TITLE
Feature Request: Fix menu position in top header

### ISSUE THREAD

**Issue by mikee2** [Dolibarr/dolibarr#7847]
# Feature Request
Fix menu position in top header

## Use case
I would like that the top menu header remain fixed at top when scrolling down the content of the pages. It is a pain to have to scroll back to the top just to select another option

## Suggested implementation
This can be easily achieved by just adding this code to the style.css.php file (at line 1215 in eldy theme for example):

div.side-nav-vert {
position: sticky;
width: 100%;
top: 0;
background-color: white;
z-index: 100;
}

## Suggested steps
Add the former code to the style.css.php file. As this is still a php file the code could be conditionally inserted based on a variable like FIX_HEADER_ON_TOP. Thus anyone could adapt the behavior to his or her own tastes.

**Comment by dolibarr95** [comment]
Hi
That's what i've done for my personnal css theme.

```css
/*menu tjrs en haut*/
.side-nav-vert
{
	height: 48px;/*I reduce the icons size, hide thext and hide print help logout menu when scroll down with javascript*/
	width: 100%;
	position: fixed;
	top: 0;
	z-index:999;
}
```

```javascript
$( window ).scroll(function() {
	 if($(window).scrollTop() > 100){
	    $('.tmenu').css({'height': '22px'}); 
		$('.tmenucenter').css({'height': '22px'}); 
		$('.tmenusel').css({'height': '22px'}); 
		$('.side-nav-vert').css({'height': '22px'}); 
		$('.topmenuimage').css({'background-size': '18px auto'}); 
		$('.mainmenuaspan').css({'display': 'none'});
		$('.login_block_other').css({'display': 'none'});
     }else{
		$('.tmenu').css({'height': '48px'}); 
		$('.tmenusel').css({'height': '48px'}); 
		$('.tmenucenter').css({'height': '48px'});
		$('.side-nav-vert').css({'height': '48px'}); 
		$('.topmenuimage').css({'background-size': '28px auto'}); 
		$('.mainmenuaspan').css({'display': ''});
		$('.login_block_other').css({'display': ''});
     }

});
```

_Not the best code practice but it's works._
